--
-- Create Schema Script 
--   Database Version   : 11.2.0.2.0 
--   Toad Version       : 10.1.1.8 
--   DB Connect String  : XE 
--   Schema             : AIRLINE 
--   Script Created by  : AIRLINE 
--   Script Created at  : 5/24/2023 3:48:30 AM 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 28        Columns: 28         
--   Tables: 17         Columns: 132        Constraints: 45     


CREATE TABLE AIRCRAFTS_DIM
(
  AIRCRAFT_KEY    NUMBER,
  AIRCRAFT_ID     VARCHAR2(100 BYTE),
  MODEL           VARCHAR2(100 BYTE),
  COMPANY         VARCHAR2(100 BYTE),
  SEATS_CAPACITY  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE AIRPORTS_DIM
(
  AIRPORT_KEY   NUMBER,
  AIRPORT_ID    VARCHAR2(100 BYTE),
  AIRPORT_NAME  VARCHAR2(100 BYTE),
  CITY          VARCHAR2(100 BYTE),
  COUNTRY       VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CHANNELS_DIM
(
  CHANNEL_KEY   NUMBER,
  CHANNEL_TYPE  VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLASS_UPGRADE_DIM
(
  CLASS_UPGRADE_KEY       NUMBER,
  CLASS_UPGRADE_ID        VARCHAR2(250 BYTE),
  PURCHASED_CLASS         VARCHAR2(250 BYTE),
  FLOWN_CLASS             VARCHAR2(250 BYTE),
  PURCHASED_FLOWN_GROUP   VARCHAR2(250 BYTE),
  CLASS_CHANGE_INDICATOR  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CUSTOMER_CARE_FACT
(
  CC_KEY                   NUMBER,
  TICKET_NUMBER            NUMBER,
  PASSENGER_KEY            NUMBER,
  FREQ_KEY                 NUMBER,
  RESERVATION_TICKET_DATE  DATE,
  SEGMENT_NUMBER           NUMBER,
  FLIGHT_KEY               NUMBER,
  INTERACTION_KEY          NUMBER,
  STAFF_KEY                NUMBER,
  PROBLEM_SEVERITY         NUMBER,
  FEEDBACK_RATE            NUMBER,
  DEPRATURE_AIRPORT        NUMBER,
  ARRIVAL_AIRPORT          NUMBER,
  SEAT_NUMBER              NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DATE_DIM
(
  FULL_DATE      DATE,
  YEAR           VARCHAR2(15 BYTE),
  QUARTER        VARCHAR2(15 BYTE),
  MONTH_NAME     VARCHAR2(15 BYTE),
  WEEK_OF_YEAR   NUMBER(6),
  WEEK_OF_MONTH  NUMBER(6),
  DAY_NAME       VARCHAR2(20 BYTE),
  DAY_NUMBER     NUMBER(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FARE_BASIS_DIM
(
  FARE_BASIS_KEY  NUMBER,
  STATUS          VARCHAR2(400 BYTE),
  CODE            VARCHAR2(100 BYTE),
  PROMOTION       VARCHAR2(150 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FLIGHTS_ACTIVITY_FACT
(
  LEG_KEY                    NUMBER,
  TICKET_NUMBER              NUMBER,
  PASSENGER_KEY              NUMBER,
  FREQ_KEY                   NUMBER,
  AIRCRAFT_KEY               NUMBER,
  SEGMENT_NUMBER             NUMBER,
  FLIGHT_KEY                 NUMBER,
  DEPARTURE_AIRPORT          NUMBER,
  ARRIVAL_AIRPORT            NUMBER,
  ACTUAL_DEPARTURE_DATE      DATE,
  SCHEDUALED_DEPARTURE_TIME  TIMESTAMP(6),
  ACTUAL_DEPARTURE_TIME      TIMESTAMP(6),
  ACTUAL_ARRIVAL_DATE        DATE,
  SCHEDUALED_ARRIVAL_TIME    TIMESTAMP(6),
  ACTUAL_ARRIVAL_TIME        TIMESTAMP(6),
  FLIGHT_DURATION            NUMBER,
  RESERVATION_TICKET_DATE    DATE,
  CHANNEL_KEY                NUMBER,
  PAYMENT_METHOD_KEY         NUMBER,
  FARE_BASIS_KEY             NUMBER,
  CLASS_UPGRADE_KEY          NUMBER,
  LUGGAGE_NUMBER             NUMBER,
  BASE_FARE_PRICE            NUMBER,
  TAXES                      NUMBER,
  OVERWEIGHT_LUGGAGE_PRICE   NUMBER,
  UPGRAGE_FEES               NUMBER,
  TRANSACTION_FEES           NUMBER,
  PROMOTION_AMOUNT           NUMBER,
  NET_PRICE                  NUMBER,
  COST                       NUMBER,
  PROFIT                     NUMBER,
  HOTEL_KEY                  NUMBER,
  OVERNIGHT_STAYS            NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FLIGHTS_DIM
(
  FLIGHT_KEY   NUMBER,
  FLIGHT_ID    VARCHAR2(250 BYTE),
  FLIGHT_ZONE  VARCHAR2(250 BYTE),
  FLIGHT_TYPE  VARCHAR2(250 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FREQUENT_FLYERS_DIM
(
  FREQ_KEY                NUMBER,
  FREQ_ID                 VARCHAR2(250 BYTE),
  TIER                    VARCHAR2(250 BYTE),
  CLUB_MEMBERSHIP_STATUS  VARCHAR2(250 BYTE),
  MILAGE_TIER             VARCHAR2(250 BYTE),
  MEMPERSHIP_STATUS       VARCHAR2(250 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FREQUENT_FLYERS_FACT
(
  FF_FACT_KEY         NUMBER,
  TICKET_NUMBER       NUMBER,
  FREQ_KEY            NUMBER,
  FLIGHT_DATE         DATE,
  FLIGHT_KEY          NUMBER,
  DEPRATURE_AIRPORT   NUMBER,
  ARRIVAL_AIRPORT     NUMBER,
  MILES_FLOWN         NUMBER,
  MILES_EARNED        NUMBER,
  PROMOTION_RESPONSE  VARCHAR2(20 BYTE),
  REDEEM_KEY          NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE HOTELS_DIM
(
  HOTEL_KEY    NUMBER,
  HOTEL_ID     VARCHAR2(50 BYTE),
  STARS        NUMBER,
  NIGHT_PRICE  NUMBER,
  CITY         VARCHAR2(20 BYTE),
  COUNTRY      VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE INTERACTIONS_DIM
(
  INTERACTION_KEY   NUMBER,
  TYPE              VARCHAR2(500 BYTE),
  INTERACTION_TIME  VARCHAR2(150 BYTE),
  DESCRIPTION       VARCHAR2(600 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PASSENGERS_DIM
(
  PASSENGER_KEY   NUMBER,
  PASSENGER_ID    VARCHAR2(250 BYTE),
  NAME            VARCHAR2(250 BYTE),
  GENDER          VARCHAR2(50 BYTE),
  PHONE           VARCHAR2(250 BYTE),
  EMAIL           VARCHAR2(250 BYTE),
  PASSENGER_TYPE  VARCHAR2(100 BYTE),
  ADDRESS         VARCHAR2(250 BYTE),
  CITY            VARCHAR2(250 BYTE),
  COUNTRY         VARCHAR2(250 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PAYMENT_METHODS_DIM
(
  P_M_KEY       NUMBER,
  PAYMENT_TYPE  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE REDEEM_DIM
(
  REDEEM_KEY   NUMBER,
  TYPE         VARCHAR2(250 BYTE),
  DESCRIPTION  VARCHAR2(500 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE STAFF_DIM
(
  STAFF_KEY   NUMBER,
  STAFF_ID    VARCHAR2(500 BYTE),
  NAME        VARCHAR2(500 BYTE),
  GENDER      VARCHAR2(20 BYTE),
  ADDRESS     VARCHAR2(250 BYTE),
  JOB_TITLE   VARCHAR2(250 BYTE),
  DEPARTMENT  VARCHAR2(250 BYTE),
  PHONE       VARCHAR2(15 BYTE),
  SUPERVISOR  VARCHAR2(80 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ACRAFT_UNQ_CONS ON AIRCRAFTS_DIM
(AIRCRAFT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX AIRCRAFT_PK_CONS ON AIRCRAFTS_DIM
(AIRCRAFT_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX AIRPORT_PK_CONS ON AIRPORTS_DIM
(AIRPORT_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APORT_UNQ_CONS ON AIRPORTS_DIM
(AIRPORT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CC_PK_CONS ON CUSTOMER_CARE_FACT
(CC_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CHANNEL_PK_CONS ON CHANNELS_DIM
(CHANNEL_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CLASSU_ID_UNQ ON CLASS_UPGRADE_DIM
(CLASS_UPGRADE_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CLASS_PK_CONS ON CLASS_UPGRADE_DIM
(CLASS_UPGRADE_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX D_PK_CONS ON DATE_DIM
(FULL_DATE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FARE_PK_CONS ON FARE_BASIS_DIM
(FARE_BASIS_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FLIGHT_PK_CONS ON FLIGHTS_DIM
(FLIGHT_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FLIGHT_UNQ_CONS ON FLIGHTS_DIM
(FLIGHT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FREQF_FACT_PK_CONS ON FREQUENT_FLYERS_FACT
(FF_FACT_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FREQ_ID_UNQ ON FREQUENT_FLYERS_DIM
(FREQ_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FREQ_PK_CONS ON FREQUENT_FLYERS_DIM
(FREQ_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX HT_PK_CONS ON HOTELS_DIM
(HOTEL_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX HT_UNQ_CONS ON HOTELS_DIM
(HOTEL_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INT_PK_CONS ON INTERACTIONS_DIM
(INTERACTION_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX LEG_PK_CONS ON FLIGHTS_ACTIVITY_FACT
(LEG_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PASSENGER_ID_UNQ ON PASSENGERS_DIM
(PASSENGER_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PASSENGER_PK_CONS ON PASSENGERS_DIM
(PASSENGER_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX P_M_PK_CONS ON PAYMENT_METHODS_DIM
(P_M_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX RD_PK_CONS ON REDEEM_DIM
(REDEEM_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ST_PK_CONS ON STAFF_DIM
(STAFF_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ST_UNQ_CONS ON STAFF_DIM
(STAFF_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TN_UNQ_CONS ON FLIGHTS_ACTIVITY_FACT
(TICKET_NUMBER)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TN_UNQ_CONSSS ON CUSTOMER_CARE_FACT
(TICKET_NUMBER)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TTN ON FREQUENT_FLYERS_FACT
(TICKET_NUMBER)
LOGGING
NOPARALLEL;


ALTER TABLE AIRCRAFTS_DIM ADD (
  CONSTRAINT AIRCRAFT_PK_CONS
 PRIMARY KEY
 (AIRCRAFT_KEY));

ALTER TABLE AIRPORTS_DIM ADD (
  CONSTRAINT AIRPORT_PK_CONS
 PRIMARY KEY
 (AIRPORT_KEY));

ALTER TABLE CHANNELS_DIM ADD (
  CONSTRAINT CHANNEL_PK_CONS
 PRIMARY KEY
 (CHANNEL_KEY));

ALTER TABLE CLASS_UPGRADE_DIM ADD (
  CONSTRAINT CLASS_PK_CONS
 PRIMARY KEY
 (CLASS_UPGRADE_KEY));

ALTER TABLE CUSTOMER_CARE_FACT ADD (
  CONSTRAINT CC_PK_CONS
 PRIMARY KEY
 (CC_KEY));

ALTER TABLE DATE_DIM ADD (
  CONSTRAINT D_PK_CONS
 PRIMARY KEY
 (FULL_DATE));

ALTER TABLE FARE_BASIS_DIM ADD (
  CONSTRAINT FARE_PK_CONS
 PRIMARY KEY
 (FARE_BASIS_KEY));

ALTER TABLE FLIGHTS_ACTIVITY_FACT ADD (
  CONSTRAINT LEG_PK_CONS
 PRIMARY KEY
 (LEG_KEY));

ALTER TABLE FLIGHTS_DIM ADD (
  CONSTRAINT FLIGHT_PK_CONS
 PRIMARY KEY
 (FLIGHT_KEY));

ALTER TABLE FREQUENT_FLYERS_DIM ADD (
  CONSTRAINT FREQ_PK_CONS
 PRIMARY KEY
 (FREQ_KEY));

ALTER TABLE FREQUENT_FLYERS_FACT ADD (
  CONSTRAINT FREQF_FACT_PK_CONS
 PRIMARY KEY
 (FF_FACT_KEY));

ALTER TABLE HOTELS_DIM ADD (
  CONSTRAINT HT_PK_CONS
 PRIMARY KEY
 (HOTEL_KEY));

ALTER TABLE INTERACTIONS_DIM ADD (
  CONSTRAINT INT_PK_CONS
 PRIMARY KEY
 (INTERACTION_KEY));

ALTER TABLE PASSENGERS_DIM ADD (
  CONSTRAINT PASSENGER_PK_CONS
 PRIMARY KEY
 (PASSENGER_KEY));

ALTER TABLE PAYMENT_METHODS_DIM ADD (
  CONSTRAINT P_M_PK_CONS
 PRIMARY KEY
 (P_M_KEY));

ALTER TABLE REDEEM_DIM ADD (
  CONSTRAINT RD_PK_CONS
 PRIMARY KEY
 (REDEEM_KEY));

ALTER TABLE STAFF_DIM ADD (
  CONSTRAINT ST_PK_CONS
 PRIMARY KEY
 (STAFF_KEY));

ALTER TABLE CUSTOMER_CARE_FACT ADD (
  CONSTRAINT AIRPORT_FK_CONSSSSS 
 FOREIGN KEY (DEPRATURE_AIRPORT) 
 REFERENCES AIRPORTS_DIM (AIRPORT_KEY),
  CONSTRAINT AIRPORT_FK_CONSSSSSSSS 
 FOREIGN KEY (ARRIVAL_AIRPORT) 
 REFERENCES AIRPORTS_DIM (AIRPORT_KEY),
  CONSTRAINT FF_FK_CONSSS 
 FOREIGN KEY (FREQ_KEY) 
 REFERENCES FREQUENT_FLYERS_DIM (FREQ_KEY),
  CONSTRAINT FLIGHT_FK_CONSSS 
 FOREIGN KEY (FLIGHT_KEY) 
 REFERENCES FLIGHTS_DIM (FLIGHT_KEY),
  CONSTRAINT INT_FK_CONSSS 
 FOREIGN KEY (INTERACTION_KEY) 
 REFERENCES INTERACTIONS_DIM (INTERACTION_KEY),
  CONSTRAINT PASS_FK_CONSSS 
 FOREIGN KEY (PASSENGER_KEY) 
 REFERENCES PASSENGERS_DIM (PASSENGER_KEY),
  CONSTRAINT RESV_T_DATE_FK_CONSSS 
 FOREIGN KEY (RESERVATION_TICKET_DATE) 
 REFERENCES DATE_DIM (FULL_DATE),
  CONSTRAINT ST_FK_CONSSS 
 FOREIGN KEY (STAFF_KEY) 
 REFERENCES STAFF_DIM (STAFF_KEY));

ALTER TABLE FLIGHTS_ACTIVITY_FACT ADD (
  CONSTRAINT ACTUAL_DATE_ARRIVAL_FK_CONS 
 FOREIGN KEY (ACTUAL_ARRIVAL_DATE) 
 REFERENCES DATE_DIM (FULL_DATE),
  CONSTRAINT ACTUAL_DATE_DEPARTURE_FK_CONS 
 FOREIGN KEY (ACTUAL_DEPARTURE_DATE) 
 REFERENCES DATE_DIM (FULL_DATE),
  CONSTRAINT AIRCRAFT_FK_CONS 
 FOREIGN KEY (AIRCRAFT_KEY) 
 REFERENCES AIRCRAFTS_DIM (AIRCRAFT_KEY),
  CONSTRAINT AIRPORT_FK_CONS 
 FOREIGN KEY (DEPARTURE_AIRPORT) 
 REFERENCES AIRPORTS_DIM (AIRPORT_KEY),
  CONSTRAINT AIRPORT_FK_CONSS 
 FOREIGN KEY (ARRIVAL_AIRPORT) 
 REFERENCES AIRPORTS_DIM (AIRPORT_KEY),
  CONSTRAINT CH_FK_CONSS 
 FOREIGN KEY (CHANNEL_KEY) 
 REFERENCES CHANNELS_DIM (CHANNEL_KEY),
  CONSTRAINT CU_FK_CONSS 
 FOREIGN KEY (CLASS_UPGRADE_KEY) 
 REFERENCES CLASS_UPGRADE_DIM (CLASS_UPGRADE_KEY),
  CONSTRAINT FB_FK_CONSS 
 FOREIGN KEY (FARE_BASIS_KEY) 
 REFERENCES FARE_BASIS_DIM (FARE_BASIS_KEY),
  CONSTRAINT FF_FK_CONS 
 FOREIGN KEY (FREQ_KEY) 
 REFERENCES FREQUENT_FLYERS_DIM (FREQ_KEY),
  CONSTRAINT FLIGHT_FK_CONS 
 FOREIGN KEY (FLIGHT_KEY) 
 REFERENCES FLIGHTS_DIM (FLIGHT_KEY),
  CONSTRAINT H_FK_CONSSS 
 FOREIGN KEY (HOTEL_KEY) 
 REFERENCES HOTELS_DIM (HOTEL_KEY),
  CONSTRAINT PASS_FK_CONS 
 FOREIGN KEY (PASSENGER_KEY) 
 REFERENCES PASSENGERS_DIM (PASSENGER_KEY),
  CONSTRAINT PM_FK_CONSS 
 FOREIGN KEY (PAYMENT_METHOD_KEY) 
 REFERENCES PAYMENT_METHODS_DIM (P_M_KEY),
  CONSTRAINT RESV_T_DATE_FK_CONSSSS 
 FOREIGN KEY (RESERVATION_TICKET_DATE) 
 REFERENCES DATE_DIM (FULL_DATE));

ALTER TABLE FREQUENT_FLYERS_FACT ADD (
  CONSTRAINT AIRPORT_FK_CONSSSSSSSSS 
 FOREIGN KEY (DEPRATURE_AIRPORT) 
 REFERENCES AIRPORTS_DIM (AIRPORT_KEY),
  CONSTRAINT AIRPORT_FK_CONSSSSSSSSSSS 
 FOREIGN KEY (ARRIVAL_AIRPORT) 
 REFERENCES AIRPORTS_DIM (AIRPORT_KEY),
  CONSTRAINT FF_FK_CONSSSS 
 FOREIGN KEY (FREQ_KEY) 
 REFERENCES FREQUENT_FLYERS_DIM (FREQ_KEY),
  CONSTRAINT FLIGHT_FK_CONSSSS 
 FOREIGN KEY (FLIGHT_KEY) 
 REFERENCES FLIGHTS_DIM (FLIGHT_KEY),
  CONSTRAINT F_DATE_FK_CONSSS 
 FOREIGN KEY (FLIGHT_DATE) 
 REFERENCES DATE_DIM (FULL_DATE),
  CONSTRAINT RD_FK_CONSSS 
 FOREIGN KEY (REDEEM_KEY) 
 REFERENCES REDEEM_DIM (REDEEM_KEY));