INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('1', 'AP-1', 'Guyuan Liupanshan Airport', 'Villa Nueva', 'Guatemala');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('2', 'AP-2', 'Andorra la Vella Heliport', 'San Francisco', 'United States');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('3', 'AP-3', 'Millicent Airport', 'Veshnyaki', 'Russia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('4', 'AP-4', 'Mackinac Island Airport', 'Luodong', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('5', 'AP-5', 'Stauning Airport', 'Baixiang', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('6', 'AP-6', 'Bauerfield International Airport', 'Siraha', 'Nepal');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('7', 'AP-7', 'Xangongo Airport', 'Sambonggede', 'Indonesia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('8', 'AP-8', 'Hokitika Airfield', 'Xiaping', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('9', 'AP-9', 'Selfridge Air National Guard Base Airport', 'Golubinci', 'Serbia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('10', 'AP-10', 'Sanfebagar Airport', 'Yuyao', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('11', 'AP-11', 'Berz-Macomb Airport', 'Karsin', 'Poland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('12', 'AP-12', 'Clovis Municipal Airport', 'Mszana Dolna', 'Poland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('13', 'AP-13', 'Chigorodó Airport', 'Fahraj', 'Iran');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('14', 'AP-14', 'Rongelap Island Airport', 'Zaragoza', 'Colombia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('15', 'AP-15', 'Cowarie Airport', 'Ustupo', 'Panama');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('16', 'AP-16', 'Nea Anchialos Airport', 'Paradyz', 'Poland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('17', 'AP-17', 'Mercedita Airport', 'Changyon', 'North Korea');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('18', 'AP-18', 'Weihai Airport', 'Tân Tru?', 'Vietnam');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('19', 'AP-19', 'Padre Aldamiz International Airport', 'Mirów', 'Poland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('20', 'AP-20', 'La Güera Airport', 'Wanglu Kulon', 'Indonesia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('21', 'AP-21', 'Muscat International Airport', 'Catumbela', 'Angola');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('22', 'AP-22', 'Colombo Ratmalana Airport', 'Ust’-Kut', 'Russia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('23', 'AP-23', 'St. Marys Airport', 'Skrunda', 'Latvia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('24', 'AP-24', 'Presidente Juscelino Kubistschek International Airport', 'Piatnica', 'Poland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('25', 'AP-25', 'Tamana Island Airport', 'Capitán Bermúdez', 'Argentina');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('26', 'AP-26', 'Robertson Airport', 'Goubangzi', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('27', 'AP-27', 'Yasser Arafat International Airport', 'Shouchang', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('28', 'AP-28', 'Egegik Airport', 'Dunkerque', 'France');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('29', 'AP-29', 'Medina Airport', 'Eg', 'Mongolia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('30', 'AP-30', 'Inhaca Airport', 'Wendo', 'Ethiopia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('31', 'AP-31', 'Sawyer International Airport', 'Sindong', 'South Korea');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('32', 'AP-32', 'Gewayentana Airport', 'Duanshen', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('33', 'AP-33', 'Lancaster Airport', 'Saharna', 'Moldova');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('34', 'AP-34', 'Tadji Airport', 'Haiyan', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('35', 'AP-35', 'Norfolk International Airport', 'Xiajiashan', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('36', 'AP-36', 'Merimbula Airport', 'Kronoby', 'Finland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('37', 'AP-37', 'Napperby Airport', 'Shishan', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('38', 'AP-38', 'Matsuyama Airport', 'Kurye', 'South Korea');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('39', 'AP-39', 'Telegraph Creek Airport', 'Cartagena', 'Colombia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('40', 'AP-40', 'Fukui Airport', 'Varkaus', 'Finland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('41', 'AP-41', 'Sabiha Gökçen International Airport', 'Aqqan', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('42', 'AP-42', 'Huangyan Luqiao Airport', 'Örebro', 'Sweden');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('43', 'AP-43', 'Capitán Aníbal Arab Airport', 'Trablice', 'Poland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('44', 'AP-44', 'Espinosa Airport', 'Donostia-San Sebastian', 'Spain');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('45', 'AP-45', 'Kairuku Airport', 'Zarrin Shahr', 'Iran');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('46', 'AP-46', 'Theda Station Airport', 'Prince Rupert', 'Canada');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('47', 'AP-47', 'Sardar Vallabhbhai Patel International Airport', 'Dongjian', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('48', 'AP-48', 'Granite Downs Airport', 'Th? Tr?n Yên Th?', 'Vietnam');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('49', 'AP-49', 'Trujillo Airport', 'Albion', 'Mauritius');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('50', 'AP-50', 'Sandringham Airport', 'Silva Jardim', 'Brazil');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('51', 'AP-51', 'Mineral Wells Airport', 'Mahekou', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('52', 'AP-52', 'Shigatse Air Base', 'Maastricht', 'Netherlands');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('53', 'AP-53', 'Longdongbao Airport', 'Gexi', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('54', 'AP-54', 'Itabuna Airport', 'Sobo', 'Indonesia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('55', 'AP-55', 'Christiansted Harbor Seaplane Base', 'Zalishchyky', 'Ukraine');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('56', 'AP-56', 'Valladolid Airport', 'Amashca', 'Peru');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('57', 'AP-57', 'Pulau Pangkor Airport', 'Castêlo', 'Portugal');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('58', 'AP-58', 'Travis Air Force Base', 'Huashan', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('59', 'AP-59', 'Bonito Airport', 'Dziemiany', 'Poland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('60', 'AP-60', 'Kindamba Airport', 'Jincheng', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('61', 'AP-61', 'New Plymouth Airport', 'Zhangdian', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('62', 'AP-62', 'Kajaani Airport', 'Rafa?', 'Egypt');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('63', 'AP-63', 'Plymouth City Airport', 'Lancheng', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('64', 'AP-64', 'Davenport Municipal Airport', 'Skopin', 'Russia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('65', 'AP-65', 'Lafayette Regional Airport', 'La Joya', 'Mexico');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('66', 'AP-66', 'Komatsu Airport', 'Dolna Banya', 'Bulgaria');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('67', 'AP-67', 'Vopnafjörður Airport', 'Penamacor', 'Portugal');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('68', 'AP-68', 'Galion Municipal Airport', 'Dahewan', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('69', 'AP-69', 'Mardin Airport', 'Rymättylä', 'Finland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('70', 'AP-70', 'Mkambati Airport', 'Batanghari', 'Indonesia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('71', 'AP-71', 'Nepalgunj Airport', 'Luohe', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('72', 'AP-72', 'Sherman Army Air Field', 'Cibungur', 'Indonesia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('73', 'AP-73', 'Gewoia Airport', 'Tarutung', 'Indonesia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('74', 'AP-74', 'Tosontsengel Airport', 'Tebon', 'Indonesia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('75', 'AP-75', 'Beaver County Airport', 'Palmitas', 'Uruguay');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('76', 'AP-76', 'Alpine Casparis Municipal Airport', 'Renhe', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('77', 'AP-77', 'Matthews Ridge Airport', 'Hallstavik', 'Sweden');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('78', 'AP-78', 'Slave Lake Airport', 'Distracción', 'Colombia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('79', 'AP-79', 'Ain Arnat Airport', 'Baniyas', 'Syria');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('80', 'AP-80', 'Camilo Daza International Airport', 'Huaiyuan Chengguanzhen', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('81', 'AP-81', 'Limon International Airport', 'Huaqiao', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('82', 'AP-82', 'King Salman Abdulaziz Airport', 'Ju?r ad Dik', 'Palestinian Territory');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('83', 'AP-83', 'Bordeaux-Mérignac Airport', 'Borne Sulinowo', 'Poland');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('84', 'AP-84', 'Gothenburg-Landvetter Airport', 'Shymkent', 'Kazakhstan');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('85', 'AP-85', 'Williamson County Regional Airport', 'Windsor', 'Canada');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('86', 'AP-86', 'Ononge Airport', 'Ribeirão', 'Brazil');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('87', 'AP-87', 'Campo do Meio Airport', 'Guri-si', 'South Korea');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('88', 'AP-88', 'Tambao Airport', 'Concepción', 'Paraguay');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('89', 'AP-89', 'Barreirinhas Airport', 'Kerrobert', 'Canada');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('90', 'AP-90', 'Mesa Del Rey Airport', 'Nhà Bàng', 'Vietnam');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('91', 'AP-91', 'Karluk Airport', 'Imider', 'Morocco');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('92', 'AP-92', 'Moussoro Airport', 'Wujingfu', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('93', 'AP-93', 'Bartolomeu Lisandro Airport', 'Maninihon', 'Philippines');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('94', 'AP-94', 'Sungai Tiang Airport', 'Taiping', 'China');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('95', 'AP-95', 'Greater Cumberland Regional Airport', 'Skovorodino', 'Russia');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('96', 'AP-96', 'Dominique Edward Osok Airport', 'Dimitsána', 'Greece');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('97', 'AP-97', 'Meselia Airport', 'Fortios', 'Portugal');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('98', 'AP-98', 'Yeniseysk Airport', 'Hanno', 'Japan');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('99', 'AP-99', 'Novo Horizonte Airport', 'Cincinnati', 'United States');
INSERT INTO Airports_Dim (Airport_key, Airport_ID, Airport_name, City, Country) VALUES ('100', 'AP-100', 'Kokhanok Airport', 'Miami', 'United States');
