INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('1', '10001', '1', to_date('12/15/2021','MM/DD/YYYY'), '1' , '1', '3', '2500', '250', 'yes', '1');


INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('2', '10002', '2', to_date('01/15/2021','MM/DD/YYYY'), '2', '2', '5', '2500', '250', 'yes', '2');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('3', '10003', '3', to_date('01/15/2021','MM/DD/YYYY'), '5', '3', '7', '2500', '250', 'no', '3');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('4', '10004', '4', to_date('01/15/2021','MM/DD/YYYY'), '4', '5', '9', '2500', '250', 'no', '2');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('5', '10005', '5', to_date('10/25/2020','MM/DD/YYYY'), '3', '4', '8' , '2000', '200', 'yes', '3');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('6', '10006', '6', to_date('10/25/2020','MM/DD/YYYY'), '2', '7', '11', '3500', '350', 'yes', '2');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('7', '10007', '7', to_date('03/10/2021','MM/DD/YYYY') , '1', '9', '20', '3000', '300', 'no', '1');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('8', '10008', '8', to_date('03/02/2021','MM/DD/YYYY'), '4', '10', '30', '3500', '350', 'no', '3');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('9', '10009', '9', to_date('03/02/2021','MM/DD/YYYY'), '2', '13', '14', '3500', '350', 'yes', '2');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('10', '10010', '10', to_date('10/10/2021','MM/DD/YYYY'), '5', '1', '7', '4600', '460', 'no', '1');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ( '11', '10011', '11', to_date('03/10/2021','MM/DD/YYYY'), '6', '5', '8', '3500', '350', 'yes', '1' );

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('12', '10012', '12', to_date('03/10/2021','MM/DD/YYYY'), '1', '15', '13', '2000', '200', 'no', '2');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('13', '10013', '13', to_date('09/09/2021','MM/DD/YYYY'), '3', '20', '30', '3500', '350', 'yes', '1');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('14', '10014', '14', to_date('09/09/2021','MM/DD/YYYY'), '4', '22', '32', '3500', '350', 'no', '1');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('15', '10015', '15', to_date('09/09/2021','MM/DD/YYYY'), '1', '17', '78', '4500', '450', 'no', '3');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('16', '10016', '16', to_date('09/01/2021','MM/DD/YYYY'), '2', '33', '55', '4000', '400', 'yes', '2');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('17', '10017', '17', to_date('12/18/2021','MM/DD/YYYY'), '3', '18', '16', '4000', '400', 'yes', '2');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('18', '10018', '18', to_date('08/20/2021','MM/DD/YYYY'), '4', '19', '11', '2000', '200', 'no', '3');

INSERT INTO Frequent_Flyers_fact (FF_FACT_KEY, TICKET_NUMBER, FREQ_KEY, FLIGHT_DATE, FLIGHT_KEY, DEPRATURE_AIRPORT, 
ARRIVAL_AIRPORT, MILES_FLOWN, MILES_EARNED, PROMOTION_RESPONSE, REDEEM_KEY) VALUES ('19', '10019', '19', to_date('08/15/2021','MM/DD/YYYY'), '6', '20', '55', '1500', '150', 'no', '1');
