INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('1', 'H-1', '5', '680', 'Manolo Fortich', 'Philippines');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('2', 'H-2', '5', '670', 'Nanzhen', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('3', 'H-3', '4', '400', 'Durham', 'United States');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('4', 'H-4', '5', '680', 'El Carmen', 'Peru');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('5', 'H-5', '3', '398', 'Olsztyn', 'Poland');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('6', 'H-6', '1', '133', 'Powassan', 'Canada');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('7', 'H-7', '4', '410', 'Bayaguana', 'Dominican Republic');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('8', 'H-8', '3', '362', 'Aparecida do Taboado', 'Brazil');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('9', 'H-9', '3', '350', 'Hammam-Lif', 'Tunisia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('10', 'H-10', '2', '200', 'Tayturka', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('11', 'H-11', '5', '688', 'Buy', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('12', 'H-12', '5', '689', 'Whitchurch', 'United Kingdom');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('13', 'H-13', '4', '420', 'Kasempa', 'Zambia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('14', 'H-14', '2', '220', 'Jetaral', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('15', 'H-15', '4', '430', 'Gaoyu', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('16', 'H-16', '3', '370', 'Aleysk', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('17', 'H-17', '1', '154', 'Shangqing', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('18', 'H-18', '1', '127', 'Pakel', 'Indonesia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('19', 'H-19', '4', '452', 'Saint Petersburg', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('20', 'H-20', '1', '347', 'Sinazongwe', 'Zambia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('21', 'H-21', '5', '655', 'Tāfuna', 'American Samoa');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('22', 'H-22', '5', '666', 'São José do Rio Preto', 'Brazil');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('23', 'H-23', '3', '360', 'Remolino', 'Colombia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('24', 'H-24', '5', '635', 'Chengmagang', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('25', 'H-25', '1', '125', 'San José de Bocay', 'Nicaragua');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('26', 'H-26', '1', '328', 'Ullulluco', 'Peru');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('27', 'H-27', '3', '341', 'Boto', 'Indonesia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('28', 'H-28', '2', '222', 'Zavety Il’icha', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('29', 'H-29', '2', '223', 'Novopokrovskaya', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('30', 'H-30', '1', '160', 'Hebeitun', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('31', 'H-31', '5', '640', 'Kemiri', 'Indonesia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('32', 'H-32', '5', '644', 'Estreito', 'Brazil');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('33', 'H-33', '4', '467', 'Rumburk', 'Czech Republic');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('34', 'H-34', '4', '440', 'Dūkštas', 'Lithuania');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('35', 'H-35', '3', '324', 'Dong’an', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('36', 'H-36', '2', '258', 'Huainan', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('37', 'H-37', '4', '450', 'Kočevje', 'Slovenia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('38', 'H-38', '3', '366', 'Anjirmuara', 'Indonesia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('39', 'H-39', '4', '460', 'Nikol’skoye', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('40', 'H-40', '2', '268', 'Dagua', 'Colombia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('41', 'H-41', '2', '278', 'Ferreñafe', 'Peru');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('42', 'H-42', '5', '645', 'Dera Bugti', 'Pakistan');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('43', 'H-43', '5', '647', 'Cernik', 'Croatia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('44', 'H-44', '5', '678', 'Morawica', 'Poland');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('45', 'H-45', '2', '254', 'Banpu', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('46', 'H-46', '1', '170', 'Cishan', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('47', 'H-47', '5', '645', 'Yerofey Pavlovich', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('48', 'H-48', '4', '470', 'Novopokrovskaya', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('49', 'H-49', '2', '236', 'Bolesławiec', 'Poland');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('50', 'H-50', '3', '356', 'Jingling', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('51', 'H-51', '2', '256', 'Huayuan', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('52', 'H-52', '2', '235', 'Karangan', 'Indonesia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('53', 'H-53', '1', '180', 'Viimsi', 'Estonia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('54', 'H-54', '4', '480', 'Jami', 'Indonesia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('55', 'H-55', '4', '490', 'Torre', 'Portugal');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('56', 'H-56', '3', '385', 'Thị Trấn Cao Lộc', 'Vietnam');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('57', 'H-57', '2', '245', 'Qinlan', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('58', 'H-58', '4', '415', 'Obiaruku Quarters', 'Nigeria');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('59', 'H-59', '2', '263', 'Xiaoguan', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('60', 'H-60', '4', '425', 'Pleasant Point', 'New Zealand');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('61', 'H-61', '1', '154', 'Sieniawa Żarska', 'Poland');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('62', 'H-62', '1', '355', 'Kuantian', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('63', 'H-63', '2', '244', 'Gaosheng', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('64', 'H-64', '5', '630', 'Peteranec', 'Croatia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('65', 'H-65', '3', '333', 'Delta del Tigre', 'Uruguay');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('66', 'H-66', '3', '387', 'Kolbuszowa', 'Poland');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('67', 'H-67', '2', '288', 'Merkezköy', 'Turkey');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('68', 'H-68', '3', '399', 'Alexandria', 'United States');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('69', 'H-69', '1', '138', 'Lagawe', 'Philippines');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('70', 'H-70', '2', '299', 'San Luis', 'Philippines');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('71', 'H-71', '2', '261', 'Machado', 'Brazil');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('72', 'H-72', '1', '174', 'Villanueva', 'Philippines');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('73', 'H-73', '2', '256', 'Kefar Shemaryahu', 'Israel');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('74', 'H-74', '5', '641', 'Moulins', 'France');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('75', 'H-75', '4', '435', 'Soras', 'Peru');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('76', 'H-76', '5', '611', 'Grande Prairie', 'Canada');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('77', 'H-77', '3', '352', 'Biograd na Moru', 'Croatia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('78', 'H-78', '3', '325', 'Jukui', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('79', 'H-79', '5', '674', 'Pasar Kidul', 'Indonesia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('80', 'H-80', '3', '344', 'Natividade', 'Brazil');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('81', 'H-81', '3', '369', 'Irákleion', 'Greece');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('82', 'H-82', '1', '156', 'HammarA', 'Sweden');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('83', 'H-83', '1', '147', 'Or Yehuda', 'Israel');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('84', 'H-84', '5', '670', 'Yuyue', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('85', 'H-85', '2', '210', 'Khatanga', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('86', 'H-86', '2', '267', 'Paatan', 'Philippines');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('87', 'H-87', '5', '677', 'Churovichi', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('88', 'H-88', '1', '165', 'Biljača', 'Serbia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('89', 'H-89', '4', '445', 'Verkhniy Mamon', 'Russia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('90', 'H-90', '4', '455', 'Chaeos', 'Portugal');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('91', 'H-91', '2', '270', 'MoglicA', 'Albania');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('92', 'H-92', '2', '252', 'Huayuan', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('93', 'H-93', '5', '678', 'Selínia', 'Greece');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('94', 'H-94', '3', '366', 'Kaltungo', 'Nigeria');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('95', 'H-95', '1', '168', 'Lingcheng', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('96', 'H-96', '4', '482', 'Mardakyany', 'Azerbaijan');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('97', 'H-97', '5', '679', 'Lyon', 'France');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('98', 'H-98', '2', '263', 'Huangyang', 'China');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('99', 'H-99', '5', '690', 'RoborA', 'Bolivia');
INSERT INTO Hotels_DIM (Hotel_key, Hotel_ID, Stars, Night_Price, City, Country) VALUES ('100', 'H-100', '1', '123', 'Neietsu', 'South Korea');
