INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('1', 'ARC-1', '7AC Champ, 7ECA Citabria', 'Champion Aircraft Corporation', '2');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('2', 'ARC-2', '7GCAA, 7GCBC, 7KCAB Citabria', 'Champion Aircraft Corporation', '2');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('3', 'ARC-3', 'Beechcraft Baron / 55 Baron', 'Beechcraft', '6');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('4', 'ARC-4', 'Beechcraft 1900', 'Beechcraft', '19');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('5', 'ARC-5', 'Beechcraft Baron / 58 Baron', 'Beechcraft', '6');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('6', 'ARC-6', 'Bell 429', 'Bell', '7');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('7', 'ARC-7', 'Bell 212', 'Bell', '15');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('8', 'ARC-8', 'Bell 412', 'Bell', '13');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('9', 'ARC-9', 'Avro RJ70', 'Avro International Aerospace', '70');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('10', 'ARC-10', 'Hawker Siddeley HS 748', 'Avro International Aerospace', '36');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('11', 'ARC-11', 'Avro RJ85', 'Avro International Aerospace', '90');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('12', 'ARC-12', 'Avro RJ100', 'Avro International Aerospace', '111');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('13', 'ARC-13', 'Airbus A319', 'Airbus', '156');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('14', 'ARC-14', 'Airbus A330-900neo', 'Airbus', '460');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('15', 'ARC-15', 'Airbus A319 (sharklets)', 'Airbus', '156');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('16', 'ARC-16', 'Airbus A318', 'Airbus', '110');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('17', 'ARC-17', 'Airbus A330-200', 'Airbus', '268');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('18', 'ARC-18', 'Airbus A320', 'Airbus', '180');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('19', 'ARC-19', 'Airbus A380-800', 'Airbus', '520');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('20', 'ARC-20', 'Airbus A310-200', 'Airbus', '230');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('21', 'ARC-21', 'Airbus A320neo', 'Airbus', '146');
INSERT INTO Aircrafts_Dim (Aircraft_key, Aircraft_ID, Model, Company, Seats_Capacity) VALUES ('22', 'ARC-22', 'Airbus A340-300', 'Airbus', '290');
